package com.concordium.sdk.responses.transactionevent.accounttransactionresults;

public enum BakerEventType {

    BAKER_ADDED,
    BAKER_REMOVED,
    BAKER_STAKE_INCREASED,
    BAKER_STAKE_DECREASED,
    BAKER_RESTAKE_EARNINGS_UPDATED,
    BAKER_KEYS_UPDATED,
    BAKER_SET_OPEN_STATUS,
    BAKER_SET_METADATA_URL,
    BAKER_SET_TRANSACTION_FEE_COMMISSION,
    BAKER_SET_BAKING_REWARD_COMMISSION,
    BAKER_SET_FINALIZATION_REWARD_COMMISSION
}
