package com.concordium.sdk.responses.transactionstatus;

enum UpdateType {
    PROTOCOL,
    MICRO_GTU_PER_EURO,
    BAKER_STAKE_THRESHOLD,
    ELECTION_DIFFICULTY,
    GAS_REWARDS,
    FOUNDATION_ACCOUNT,
    TRANSACTION_FEE_DISTRIBUTION,
    EURO_PER_ENERGY,
    ROOT,
    LEVEL_1,
    LEVEL_2,
    MINT_DISTRIBUTION,
    ADD_ANONYMITY_REVOKER,
    ADD_IDENTITY_PROVIDER,
    POOL_PARAMETERS,
    MINT_DISTRIBUTION_CPV1,
    TIME_PARAMETERS_CPV1,
    COOLDOWN_PARAMETERS_CPV1,
}
