package com.concordium.sdk.responses.blocksummary.updates.queues;

public enum PendingUpdateType {
    Level1Keys,
    Protocol,
    ElectionDifficulty,
    EuroPerEnergy,
    MicroCcdPerEuro,
    FoundationAccount,
    TransactionFeeDistribution,
    GasRewards,
    Level2CpV0Keys,
    Level2CpV1Keys,
    MintDistributionCpV1,
    MintDistributionCpV0,
    PoolParametersCpV0,
    PoolParametersCpV1,
    AddAnonymityRevoker,
    AddIdentityProvider,
    CoolDownParameters,
    TimeParameters,
    GasRewardsCpV2,
    TimeoutParameters,
    BlockEnergyLimit,
    MinBlockTime,
    RootKeys,
    FinalizationCommitteeParameters,
}
