package com.concordium.sdk.transactions;

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NonNull;
import lombok.ToString;

import static com.google.common.primitives.Bytes.concat;

@Getter
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public abstract class AbstractAccountTransaction extends BlockItem {

    /**
     * Header for the transaction
     */
    private final TransactionHeader header;

    /**
     * Signature of the transaction. Signature is generated by an Account Holder by Signing the Transaction body.
     */
    private final TransactionSignature signature;

    /**
     * The type of the Account Transaction.
     */
    private final TransactionType transactionType;

    /**
     * Account Transaction Payload Serialized to bytes.
     */
    private final byte[] payloadBytes;

    AbstractAccountTransaction(
            @NonNull final AccountAddress sender,
            @NonNull final AccountNonce nonce,
            @NonNull final Expiry expiry,
            @NonNull final TransactionSigner signer,
            @NonNull final Payload payload) {
        this(payload
                .withHeader(TransactionHeader.builder()
                        .sender(sender)
                        .accountNonce(nonce.getNonce())
                        .expiry(expiry.getValue())
                        .build())
                .signWith(signer));
    }

    AbstractAccountTransaction(
            @NonNull final TransactionHeader header,
            @NonNull final TransactionSignature signature,
            @NonNull final Payload payload) {
        this(header, signature, payload.getTransactionType(), payload.getTransactionPayloadBytes());
    }

    AbstractAccountTransaction(Payload payload) {
        this(payload.header, payload.signature, payload.getTransactionType(), payload.getTransactionPayloadBytes());
    }

    AbstractAccountTransaction(
            @NonNull final TransactionHeader header,
            @NonNull final TransactionSignature signature,
            @NonNull final TransactionType transactionType,
            final byte @NonNull [] payloadBytes) {
        super(BlockItemType.ACCOUNT_TRANSACTION);
        this.header = header;
        this.signature = signature;
        this.payloadBytes = payloadBytes;
        this.transactionType = transactionType;
    }

    /**
     * Sender of this Transaction.
     *
     * @return {@link AccountAddress} of the sender account.
     */
    public AccountAddress getSender() {
        return this.header.getSender();
    }

    /**
     * Sequence number for Account Activity. This should increase monotonically.
     *
     * @return {@link AccountNonce}.
     */
    public AccountNonce getNonce() {
        return AccountNonce.from(this.header.getAccountNonce());
    }

    /**
     * Indicates when the transaction should expire.
     */
    public Expiry getExpiry() {
        return Expiry.from(this.header.getExpiry().getValue());
    }

    final byte[] getBlockItemBytes() {
        return concat(signature.getBytes(),
                header.getBytes(),
                new byte[]{getTransactionType().getValue()},
                payloadBytes);
    }
}
