package com.concordium.sdk.transactions;

import com.concordium.sdk.crypto.SHA256;
import com.concordium.sdk.types.AccountAddress;
import com.concordium.sdk.types.Nonce;
import com.concordium.sdk.types.UInt64;
import lombok.*;

import java.nio.ByteBuffer;

import static com.google.common.primitives.Bytes.concat;

@Getter
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class AccountTransaction extends BlockItem {

    /**
     * Header for the transaction
     */
    private final TransactionHeader header;

    /**
     * Signature of the transaction. Signature is generated by an Account Holder by Signing the Transaction body.
     */
    private final TransactionSignature signature;

    /**
     * Account Transaction Payload Serialized to bytes.
     */
    private final Payload payload;

    /**
     * Constructor serializing an account transaction
     *
     * @param sender        sender of the transaction
     * @param nonce         account nonce
     * @param expiry        the expiry of the transaction
     * @param signer        the {@link Signer} of the transaction
     * @param payload       the payload of the transaction
     * @param maxEnergyCost the max energy cost allowed for this transaction.
     */
    AccountTransaction(
            @NonNull final AccountAddress sender,
            @NonNull final Nonce nonce,
            @NonNull final Expiry expiry,
            @NonNull final TransactionSigner signer,
            @NonNull final Payload payload,
            @NonNull UInt64 maxEnergyCost) {
        this(payload
                .withHeader(TransactionHeader.explicitMaxEnergyBuilder()
                        .sender(sender)
                        .Nonce(nonce)
                        .expiry(expiry.getValue())
                        .maxEnergyCost(maxEnergyCost)
                        .build())
                .signWith(signer));
    }

    /**
     * Constructor for deserializing a transaction
     *
     * @param signature the signature
     * @param header    the header
     * @param payload   the payload
     */
    public AccountTransaction(
            @NonNull final TransactionSignature signature,
            @NonNull final TransactionHeader header,
            @NonNull final Payload payload) {
        this(header, signature, payload);
    }

    AccountTransaction(Payload payload) {
        this(payload.header, payload.signature, payload);
    }

    @Builder(
            builderMethodName = "builderAccountTransactionBlockItem",
            builderClassName = "AccountTransactionBlockItemBuilder")
    AccountTransaction(
            @NonNull final TransactionHeader header,
            @NonNull final TransactionSignature signature,
            @NonNull final Payload payload) {
        super(BlockItemType.ACCOUNT_TRANSACTION);
        this.header = header;
        this.signature = signature;
        this.payload = payload;
    }


    /**
     * Sender of this Transaction.
     *
     * @return {@link AccountAddress} of the sender account.
     */
    public AccountAddress getSender() {
        return this.header.getSender();
    }

    /**
     * Sequence number for Account Activity. This should increase monotonically.
     *
     * @return {@link Nonce}.
     */
    public Nonce getNonce() {
        return this.header.getNonce();
    }

    /**
     * Indicates when the transaction should expire.
     */
    public Expiry getExpiry() {
        return Expiry.from(this.header.getExpiry().getValue());
    }

    final byte[] getBlockItemBytes() {
        return concat(signature.getBytes(), header.getBytes(), getPayload().getBytes());
    }

    /**
     * @param source a buffer to read transaction bytes from, without {@link BlockItemType} byte.
     * @return deserialized {@link AccountTransaction}
     * @throws UnsupportedOperationException if payload can't be read.
     *                                       Not all transaction (payload) types can be read.
     *                                       For unsupported types, get the payload size
     *                                       from the manually read {@link TransactionHeader}
     *                                       and then proceed with {@link RawPayload}.
     */
    public static AccountTransaction fromBytes(ByteBuffer source) {
        return new AccountTransaction(
                TransactionSignature.fromBytes(source),
                TransactionHeader.fromBytes(source),
                Payload.fromBytes(source)
        );
    }

    public static byte[] getDataToSign(
            TransactionHeader header,
            Payload payload
    ) {
        return SHA256.hash(
                concat(
                        header.getBytes(),
                        payload.getBytes()
                )
        );
    }
}
